
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: aaron
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090
